version: "3.9"

services:
  ctransaction:
    platform: linux/amd64
    build:
      context: transaction-ms/.
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 9007
      DATABASE_HOST: db.ms.local
      DATABASE_PORT: 3306
      DATABASE_NAME: transaction_ms
      DATABASE_USER: root
      DATABASE_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
      AUTHORIZATION_MS_HOST: authorization.ms.local
      AUTHORIZATION_MS_PORT: 50051
      REDIS_QUEUE_HOST: redis.ms.local
      REDIS_QUEUE_PORT: 6379
      REDIS_QUEUE_TRANSACTION_TOPIC_NAME: transactions
    networks:
      - ms_network
    hostname: transaction.ms.local
    ports:
      - 9007:9007
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "9007"]
      interval: 3s
      timeout: 1s
      retries: 20
  cauthorization:
    platform: linux/amd64
    build:
      context: authorization-ms/.
      dockerfile: Dockerfile
    networks:
      - ms_network
    hostname: authorization.ms.local
    ports:
      - 50051:50051
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "50051"]
      interval: 3s
      timeout: 1s
      retries: 20
  cnotification:
    platform: linux/amd64
    build:
      context: notification-ms/.
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_QUEUE_HOST: redis.ms.local
      REDIS_QUEUE_PORT: 6379
      REDIS_QUEUE_TRANSACTION_TOPIC_NAME: transactions
    networks:
      - ms_network
    hostname: notification.ms.local
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
      MARIADB_DATABASE: transaction_ms
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ms_network
    hostname: db.ms.local
    ports:
      - 13306:3306
    healthcheck:
      test: mysqladmin -p13152c0e-ce51-4e03-bebd-8e2c4fb359bf ping -h localhost
      start_period: 5s
      interval: 3s
      timeout: 1s
      retries: 20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db.ms.local
      PMA_USER: root
      PMA_PASSWORD: 13152c0e-ce51-4e03-bebd-8e2c4fb359bf
    networks:
      - ms_network
    hostname: phpmyadmin.ms.local
    ports:
      - 13307:80
    healthcheck:
      test: ["CMD", "curl", "--connect-timeout", "1", "-s", "http://127.0.0.1"]
      interval: 3s
      timeout: 1s
      retries: 20
  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - ms_network
    hostname: redis.ms.local
    ports:
      - 16379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 3s
      timeout: 1s
      retries: 20
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOSTS: redis.ms.local:redis.ms.local:6379
    networks:
      - ms_network
    hostname: redis-commander.ms.local
    ports:
      - 16380:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  db_data:
  redis_data:

networks:
  ms_network:
    driver: bridge